-- An account stops being its email address.
--
-- Orders carried no account id: "my orders" was answered by string-matching
-- `orders.email` against the signed-in account's email, and so were
-- verified-purchase reviews, the buyer's chat threads, and order claiming.
-- The effect was that changing your email silently took all of it away, and
-- claiming an order had to *rewrite* the order's email to work - overwriting
-- the record of what the buyer actually typed at checkout.
--
-- So identity moves onto the account itself:
--   * `users.public_id` is a permanent, quotable handle for the account that
--     nothing keys on changing - email, phone and username all become things
--     a person may edit freely.
--   * `orders.user_id` is who placed the order. The email stays as a record
--     of what was typed, no longer as the identity.
--
-- Existing orders are linked by the email they were placed with, which is
-- exactly the rule the old queries used - so nobody's history moves.
--
-- Idempotent by convention: re-running changes nothing.

-- ── A permanent public id for every account ───────────────────────
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "public_id" varchar(16);--> statement-breakpoint

-- Backfill: derived from the row's uuid, so it is unique without a retry loop
-- and stable if this runs twice. New accounts get a random one from the app.
UPDATE "users"
   SET "public_id" = 'HM' || upper(substr(replace("id"::text, '-', ''), 1, 8))
 WHERE "public_id" IS NULL;--> statement-breakpoint

-- Generated by the database, so no code path that creates an account can
-- forget it - and there are three of them (signup, inline checkout, Google).
ALTER TABLE "users" ALTER COLUMN "public_id"
  SET DEFAULT ('HM' || upper(substr(md5(gen_random_uuid()::text), 1, 8)));--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "public_id" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "users_public_id_unique_idx"
  ON "users" ("public_id");--> statement-breakpoint

-- ── Orders point at the account that placed them ──────────────────
ALTER TABLE "orders"
  ADD COLUMN IF NOT EXISTS "user_id" uuid REFERENCES "users"("id") ON DELETE set null;--> statement-breakpoint

-- Link the history that already exists, by the same rule the old email match
-- used. Only where exactly one account owns that address, so an ambiguous
-- match is left null rather than guessed at.
UPDATE "orders" o
   SET "user_id" = u."id"
  FROM "users" u
 WHERE o."user_id" IS NULL
   AND u."email" IS NOT NULL
   AND lower(o."email") = lower(u."email")
   AND (
     SELECT count(*) FROM "users" u2
      WHERE u2."email" IS NOT NULL AND lower(u2."email") = lower(o."email")
   ) = 1;--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "orders_user_idx" ON "orders" ("user_id", "placed_at");
